version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile.web
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env.db
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - ./pgbackups:/backups
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env.db
    environment:
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@midnight
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080

