version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile.web
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env.db
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql

